apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-prod
  labels:
    name: amazon-app
  annotations:
    cert-manager.io/issuer: letsencrypt-nginx
spec:
  tls:
  - hosts:
    - amazon.micofiontech.fun
    secretName: letsencrypt-nginx
  rules:
  - host: amazon.micofiontech.fun
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: amazon-service
            port:
              number: 3000
  ingressClassName: nginx
